name: Jupyter Book Build

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book
      - name: Build Jupyter Book
        run: |
          cd GeothermalEnergy/
          jupyter-book build .
        working-directory: ./
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build Jupyter Book
          commit_options: '--author "GitHub Actions <actions@github.com>"'
          commit_user: 'GitHub Actions'
          commit_email: 'actions@github.com'
          branch: ${{ github.head_ref }}

